"""
Append-only file store for generated reports and uploaded documents.

- Files live outside the web root: ``MADZI_FILE_STORE`` or ``data/files`` (never app/static).
- Names are generated by the app (random hex); a user-supplied file name is metadata only.
- Every file is written once (exclusive create) and never overwritten or deleted by the app;
  its SHA-256 is recorded by the caller and checked again on every read.
- Files are sharded into two-level folders to keep directories small.
"""
from __future__ import annotations

import hashlib
import os
import secrets
from pathlib import Path

from app.core.config import DATA_DIR
from app.platform.errors import Conflict, NotFound


def root() -> Path:
    base = Path(os.getenv("MADZI_FILE_STORE") or (DATA_DIR / "files"))
    base.mkdir(parents=True, exist_ok=True)
    return base


def _path(name: str) -> Path:
    if not name or not all(c in "0123456789abcdef" for c in name) or len(name) != 32:
        raise NotFound("Stored file not found.")
    return root() / name[:2] / name[2:4] / name


def put(data: bytes) -> tuple[str, str, int]:
    """Store bytes; returns (storage name, sha256, size)."""
    name = secrets.token_hex(16)
    path = _path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "xb") as f:          # exclusive: an existing file is never replaced
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    try:
        os.chmod(path, 0o444)            # read-only where the OS honours it
    except OSError:
        pass
    return name, hashlib.sha256(data).hexdigest(), len(data)


def get(name: str, sha256: str) -> bytes:
    """Read a stored file, refusing it if its content no longer matches the recorded hash."""
    path = _path(name)
    if not path.exists():
        raise NotFound("Stored file not found.")
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != sha256:
        raise Conflict("Integrity check failed: the stored file does not match its recorded fingerprint. "
                       "Restore it from backup and report the incident.")
    return data


def verify(name: str, sha256: str) -> bool:
    try:
        get(name, sha256)
        return True
    except (NotFound, Conflict):
        return False
