"""shared governance foundation

Periods, organisational scope (user_org_roles, user_functions), append-only audit
events, approval steps, actions, entity links, comments and notifications.

Access becomes deny-by-default. So that an upgrade does not silently take access
away, every existing non-admin account is granted organisation-wide *viewer* scope
(the access it had before), and each grant is written to the audit trail.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 23:57:16.740104
"""
from __future__ import annotations

from datetime import datetime

from alembic import op
import sqlalchemy as sa

from app.platform.sqlguards import append_only


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.String(length=40), nullable=True),
    sa.Column('progress_note', sa.Text(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.String(length=60), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_org_unit_code'), ['org_unit_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_owner'), ['owner'], unique=False)
        batch_op.create_index('ix_actions_source', ['source_type', 'source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    op.create_table('approval_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('step', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.create_index('ix_approval_steps_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('author', sa.String(length=60), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('ix_comments_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('entity_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_type', sa.String(length=40), nullable=False),
    sa.Column('from_id', sa.String(length=40), nullable=False),
    sa.Column('to_type', sa.String(length=40), nullable=False),
    sa.Column('to_id', sa.String(length=40), nullable=False),
    sa.Column('to_version', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_type', 'from_id', 'to_type', 'to_id', 'relation', 'to_version', name='uq_entity_link')
    )
    with op.batch_alter_table('entity_links', schema=None) as batch_op:
        batch_op.create_index('ix_entity_links_from', ['from_type', 'from_id'], unique=False)
        batch_op.create_index('ix_entity_links_to', ['to_type', 'to_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'dedupe_key', name='uq_notification_dedupe')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_username'), ['username'], unique=False)

    op.create_table('periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'start_date', name='uq_period_type_start')
    )
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periods_fiscal_year'), ['fiscal_year'], unique=False)

    op.create_table('user_functions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(length=40), nullable=False),
    sa.Column('granted_by', sa.String(length=60), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'function', name='uq_user_function')
    )
    with op.batch_alter_table('user_functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_functions_user_id'), ['user_id'], unique=False)

    op.create_table('user_org_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('granted_by', sa.String(length=60), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_unit_code', name='uq_user_org_role')
    )
    with op.batch_alter_table('user_org_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_org_roles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
    append_only("audit_events")
    _grant_existing_users()


def _grant_existing_users() -> None:
    bind = op.get_bind()
    now = datetime.utcnow()
    users = bind.execute(sa.text("SELECT id, username FROM users WHERE role <> 'admin'")).fetchall()
    grants = sa.table("user_org_roles", sa.column("user_id", sa.Integer), sa.column("org_unit_code", sa.String),
                      sa.column("role", sa.String), sa.column("granted_by", sa.String),
                      sa.column("granted_at", sa.DateTime))
    events = sa.table("audit_events", sa.column("at", sa.DateTime), sa.column("actor", sa.String),
                      sa.column("action", sa.String), sa.column("entity_type", sa.String),
                      sa.column("entity_id", sa.String), sa.column("after", sa.JSON), sa.column("reason", sa.Text))
    for uid, username in users:
        op.bulk_insert(grants, [{"user_id": uid, "org_unit_code": "org", "role": "viewer",
                                 "granted_by": "migration:0002", "granted_at": now}])
        op.bulk_insert(events, [{"at": now, "actor": "migration:0002", "action": "access.update",
                                 "entity_type": "user", "entity_id": str(uid),
                                 "after": {"grants": [{"org_unit_code": "org", "role": "viewer"}]},
                                 "reason": f"Kept existing organisation-wide read access for {username} "
                                           "when access became deny-by-default."}])


def downgrade() -> None:
    # Dropping these tables would destroy the audit trail and every grant.
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
