"""strategy and M&E

Plans with configurable level labels, plan nodes (results and delivery trees),
the indicator reference sheet, reporting cycles and assignments, append-only
progress updates and data-quality assessments, evaluations and management
responses. metric_targets gains plan_id (the plan that set the target).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 00:27:42.630041
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.sqlguards import append_only


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_fy', sa.Integer(), nullable=False),
    sa.Column('end_fy', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('lead', sa.String(length=60), nullable=True),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_plan_id'), ['plan_id'], unique=False)

    op.create_table('plan_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('plural', sa.String(length=60), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'node_type', name='uq_plan_level')
    )
    with op.batch_alter_table('plan_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_levels_plan_id'), ['plan_id'], unique=False)

    op.create_table('plan_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['plan_nodes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'code', name='uq_plan_node_code')
    )
    with op.batch_alter_table('plan_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_nodes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_nodes_plan_id'), ['plan_id'], unique=False)

    op.create_table('reporting_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('opens_on', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('require_verification', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'period_id', name='uq_cycle_plan_period')
    )
    with op.batch_alter_table('reporting_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reporting_cycles_plan_id'), ['plan_id'], unique=False)

    op.create_table('indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('metric_code', sa.String(length=80), nullable=False),
    sa.Column('polarity', sa.String(length=12), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('aggregation', sa.String(length=10), nullable=False),
    sa.Column('formula_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('reporting_units', sa.JSON(), nullable=True),
    sa.Column('collection', sa.String(length=10), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('baseline_date', sa.Date(), nullable=True),
    sa.Column('target_basis', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('dq_notes', sa.Text(), nullable=True),
    sa.Column('valid_min', sa.Float(), nullable=True),
    sa.Column('valid_max', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['plan_nodes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'code', name='uq_indicator_code')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_plan_id'), ['plan_id'], unique=False)

    op.create_table('management_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_by', sa.String(length=60), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('management_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_management_responses_evaluation_id'), ['evaluation_id'], unique=False)

    op.create_table('cycle_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('contributor', sa.String(length=60), nullable=True),
    sa.Column('reviewer', sa.String(length=60), nullable=True),
    sa.Column('approver', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('current_update_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['reporting_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'indicator_id', 'org_unit_code', name='uq_cycle_assignment')
    )
    with op.batch_alter_table('cycle_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_assignments_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_assignments_indicator_id'), ['indicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_assignments_org_unit_code'), ['org_unit_code'], unique=False)

    op.create_table('progress_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('value_state', sa.String(length=15), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('forecast', sa.Float(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('variance_reason', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('value_source', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.String(length=60), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['cycle_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'revision', name='uq_update_revision')
    )
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_updates_assignment_id'), ['assignment_id'], unique=False)

    op.create_table('dqa_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('check', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=6), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=60), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['progress_updates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dqa_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dqa_assessments_update_id'), ['update_id'], unique=False)

    with op.batch_alter_table('metric_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_metric_targets_plan_id'), ['plan_id'], unique=False)
        batch_op.create_foreign_key('fk_metric_targets_plan_id', 'plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###
    append_only("progress_updates")
    append_only("dqa_assessments")


def downgrade() -> None:
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
