"""scorecard engine

Versioned scoring schemes with five explicit bands, and score snapshots that
freeze their inputs (value and target ids, weights, scheme and engine version,
inputs hash) and result. The proposed default scheme is created as a draft on
first use, so it is signed off before any score is approved.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 00:53:09.366338
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('rating_order', sa.String(length=20), nullable=False),
    sa.Column('cap_pct', sa.Float(), nullable=False),
    sa.Column('zero_target_rule', sa.String(length=12), nullable=False),
    sa.Column('lower_method', sa.String(length=20), nullable=False),
    sa.Column('missing_policy', sa.String(length=20), nullable=False),
    sa.Column('coverage_gate_pct', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_scheme_version')
    )
    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('scheme_version', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provisional', sa.Integer(), nullable=False),
    sa.Column('achievement', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_label', sa.String(length=60), nullable=True),
    sa.Column('completeness_pct', sa.Float(), nullable=True),
    sa.Column('covered_weight', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scoring_schemes.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['score_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_score_snapshots_scope', ['plan_id', 'period_id', 'org_unit_code'], unique=False)

    op.create_table('scoring_bands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('min_achievement', sa.Float(), nullable=False),
    sa.Column('max_achievement', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['scoring_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring_bands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_bands_scheme_id'), ['scheme_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
