"""reporting hub

Report templates, report instances (frozen normalised data with its
fingerprint, commentary, approval lifecycle and content fingerprint), stored
and hashed outputs (HTML, PDF, XLSX), and an append-only access log.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 07:23:15.506398
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.sqlguards import append_only


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=15), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_report_template_version')
    )
    op.create_table('report_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('audience', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('data_hash', sa.String(length=64), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('score_snapshot_ids', sa.JSON(), nullable=True),
    sa.Column('commentary', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.String(length=60), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.String(length=60), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_instances_org_unit_code'), ['org_unit_code'], unique=False)

    op.create_table('report_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=5), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_name', sa.String(length=40), nullable=False),
    sa.Column('generated_by', sa.String(length=60), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['report_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'format', 'content_hash', name='uq_report_output')
    )
    with op.batch_alter_table('report_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_outputs_instance_id'), ['instance_id'], unique=False)

    op.create_table('report_access_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('output_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['report_instances.id'], ),
    sa.ForeignKeyConstraint(['output_id'], ['report_outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_access_log_instance_id'), ['instance_id'], unique=False)

    # ### end Alembic commands ###
    append_only("report_access_log")


def downgrade() -> None:
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
