"""document control

Document types, documents (controlled: number, revision, owner, approver,
classification, effective and review dates) and append-only document
versions (file fingerprint, extracted text, extraction status). On SQLite a
full-text search table (FTS5, document_fts) is created; it has no ORM model
and is excluded from `alembic check` (see app.migrate.include_object).

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-25 07:40:40.810554
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.sqlguards import append_only


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('controlled', sa.Boolean(), nullable=False),
    sa.Column('number_prefix', sa.String(length=10), nullable=True),
    sa.Column('review_interval_months', sa.Integer(), nullable=True),
    sa.Column('allowed_extensions', sa.JSON(), nullable=False),
    sa.Column('metadata_fields', sa.JSON(), nullable=True),
    sa.Column('default_classification', sa.String(length=15), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('owner', sa.String(length=60), nullable=False),
    sa.Column('approver', sa.String(length=60), nullable=True),
    sa.Column('classification', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('approved_version', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'revision', name='uq_document_number_revision')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_org_unit_code'), ['org_unit_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_type_id'), ['type_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_name', sa.String(length=40), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=12), nullable=False),
    sa.Column('extraction_error', sa.String(length=300), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=60), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_version')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###
    append_only("document_versions")
    if op.get_bind().dialect.name == "sqlite":
        op.execute("CREATE VIRTUAL TABLE IF NOT EXISTS document_fts USING fts5("
                   "version_id UNINDEXED, document_id UNINDEXED, title, body, tokenize='unicode61')")


def downgrade() -> None:
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
