"""governance and risk

Meetings and resolutions, audit findings (auditor and management fields
kept apart), organisation-defined risk matrices (any size), risks, risk
controls and an append-only history of risk assessments.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 08:05:07.554149
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.sqlguards import append_only


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=30), nullable=False),
    sa.Column('audit_name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('auditor', sa.String(length=60), nullable=False),
    sa.Column('owner', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('management_response', sa.Text(), nullable=True),
    sa.Column('agreed_due_date', sa.Date(), nullable=True),
    sa.Column('responded_by', sa.String(length=60), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('closure_note', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=60), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('audit_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_findings_org_unit_code'), ['org_unit_code'], unique=False)

    op.create_table('risk_matrices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('likelihood_levels', sa.JSON(), nullable=False),
    sa.Column('impact_levels', sa.JSON(), nullable=False),
    sa.Column('bands', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('inherent_l', sa.Integer(), nullable=True),
    sa.Column('inherent_i', sa.Integer(), nullable=True),
    sa.Column('residual_l', sa.Integer(), nullable=True),
    sa.Column('residual_i', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['risk_matrices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_org_unit_code'), ['org_unit_code'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('minutes_document_id', sa.Integer(), nullable=True),
    sa.Column('secretary', sa.String(length=60), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['minutes_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=60), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_risk_id'), ['risk_id'], unique=False)

    op.create_table('risk_controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_type', sa.String(length=12), nullable=False),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('effectiveness', sa.String(length=15), nullable=False),
    sa.Column('last_tested', sa.Date(), nullable=True),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_controls_risk_id'), ['risk_id'], unique=False)

    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('implementation_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolutions_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###
    append_only("risk_assessments")


def downgrade() -> None:
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
