"""regulator packs

Regulator packs (versioned, source-cited, draft/approved/retired), regulatory
returns with append-only raw values, and saved league-table runs.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-25 08:08:42.922609
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.sqlguards import append_only


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulator_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regulator', sa.String(length=40), nullable=False),
    sa.Column('jurisdiction', sa.String(length=60), nullable=False),
    sa.Column('cycle', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_accessed', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('imported_by', sa.String(length=60), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=60), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulator', 'cycle', 'version', name='uq_regulator_pack_version')
    )
    op.create_table('regulatory_returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('submitted_by', sa.String(length=60), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['regulator_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulatory_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulatory_returns_pack_id'), ['pack_id'], unique=False)

    op.create_table('league_table_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('pack_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['regulator_packs.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['regulatory_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('league_table_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_table_runs_pack_id'), ['pack_id'], unique=False)

    op.create_table('return_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=40), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=60), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['return_id'], ['regulatory_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_values_return_id'), ['return_id'], unique=False)

    # ### end Alembic commands ###
    append_only("return_values")


def downgrade() -> None:
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
