"""performance contracts and appraisal

HR policy confirmations (the gate for the people modules), performance
contracts with their weighted indicator items, and staff appraisals. These
records are private to the people named on them and HR officers.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-25 08:10:50.623577
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_policy_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('policy_ref', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=60), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_appraisals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee', sa.String(length=60), nullable=False),
    sa.Column('appraiser', sa.String(length=60), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=False),
    sa.Column('self_assessment', sa.JSON(), nullable=True),
    sa.Column('appraiser_assessment', sa.JSON(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('employee_comment', sa.Text(), nullable=True),
    sa.Column('appeal_reason', sa.Text(), nullable=True),
    sa.Column('appeal_decision', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_appraisals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_appraisals_appraiser'), ['appraiser'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_appraisals_employee'), ['employee'], unique=False)

    op.create_table('performance_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_code', sa.String(length=80), nullable=False),
    sa.Column('holder', sa.String(length=60), nullable=False),
    sa.Column('supervisor', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('final_rating', sa.Float(), nullable=True),
    sa.Column('final_label', sa.String(length=60), nullable=True),
    sa.Column('appeal_reason', sa.Text(), nullable=True),
    sa.Column('appeal_decision', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_contracts_org_unit_code'), ['org_unit_code'], unique=False)

    op.create_table('contract_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['performance_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_items_contract_id'), ['contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Downgrades are not supported; restore the backup taken before the upgrade.")
