"""
Render a laid-out report (see layout.py) to HTML, PDF or XLSX. Same blocks, same content.

- HTML is the accessible format: real headings, captioned tables with header cells, a
  language attribute and print styles.
- PDF uses reportlab (pure Python, no system libraries; chosen for Windows installs).
  Reportlab's built-in fonts cover Latin-1, so a few symbols are written out in words.
  The PDF is not tagged for screen readers; the HTML output is the accessible version.
- XLSX: a "Report" sheet with every block, plus one sheet per table.
"""
from __future__ import annotations

import io
from html import escape

TONE_CLASS = {"warn": "warn", "note": "note", "normal": ""}


# ── HTML ────────────────────────────────────────────────────────────────────

def to_html(blocks: list[dict], meta: dict) -> bytes:
    parts = []
    for b in blocks:
        t = b["t"]
        if t == "h":
            parts.append(f"<h{b['level']}>{escape(b['text'])}</h{b['level']}>")
        elif t == "p":
            cls = TONE_CLASS.get(b.get("tone", "normal"), "")
            role = ' role="note"' if cls else ""
            parts.append(f'<p class="{cls}"{role}>{escape(b["text"]).replace(chr(10), "<br>")}</p>')
        elif t == "kv":
            parts.append("<dl>" + "".join(f"<dt>{escape(k)}</dt><dd>{escape(v)}</dd>" for k, v in b["items"]) + "</dl>")
        elif t == "table":
            num = set(b.get("num", []))
            head = "".join(f'<th scope="col"{" class=num" if i in num else ""}>{escape(c)}</th>'
                           for i, c in enumerate(b["columns"]))
            rows = "".join("<tr>" + "".join(f'<td{" class=num" if i in num else ""}>{escape(str(v))}</td>'
                                             for i, v in enumerate(r)) + "</tr>" for r in b["rows"])
            body = rows or f'<tr><td colspan="{len(b["columns"])}">None.</td></tr>'
            parts.append(f'<table><caption>{escape(b["caption"])}</caption><thead><tr>{head}</tr></thead>'
                         f"<tbody>{body}</tbody></table>")
    status = meta["status"]
    banner = "" if status in ("approved", "published") else \
        f'<div class="banner" role="note">{escape(status.replace("_", " ").upper())} — NOT APPROVED</div>'
    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(meta['title'])}</title>
<style>
body{{font-family:Inter,Segoe UI,Arial,sans-serif;color:#111827;margin:24px;max-width:1100px;line-height:1.5;font-size:14px}}
h1{{font-size:24px;margin:0 0 12px;color:#142E49}} h2{{font-size:17px;margin:26px 0 8px;color:#142E49;border-bottom:1px solid #d1d5db;padding-bottom:4px}}
dl{{display:grid;grid-template-columns:max-content 1fr;gap:4px 16px;margin:8px 0}} dt{{font-weight:600;color:#374151}} dd{{margin:0}}
table{{border-collapse:collapse;width:100%;margin:8px 0 16px;font-size:13px}} caption{{text-align:left;font-weight:600;color:#374151;padding:4px 0}}
th,td{{border:1px solid #d1d5db;padding:5px 8px;text-align:left;vertical-align:top}} th{{background:#f3f4f6}}
.num{{text-align:right;white-space:nowrap}} p.warn{{background:#fffbeb;border:1px solid #d97706;padding:8px 10px;border-radius:6px}}
p.note{{color:#4b5563;font-style:italic}} .banner{{background:#7f1d1d;color:#fff;font-weight:700;padding:6px 10px;margin-bottom:12px;letter-spacing:.05em}}
footer{{margin-top:28px;font-size:12px;color:#4b5563;border-top:1px solid #d1d5db;padding-top:8px}}
@media print{{body{{margin:0}} h2{{break-after:avoid}} table{{break-inside:auto}} tr{{break-inside:avoid}}}}
</style></head><body><main>{banner}{''.join(parts)}</main>
<footer>{escape(meta.get('organisation') or '')} · Report #{meta['id']} · content fingerprint {escape(meta.get('content_hash') or meta['data_hash'])[:16]} · generated by MadziHub</footer>
</body></html>"""
    return html.encode("utf-8")


# ── PDF ─────────────────────────────────────────────────────────────────────

_PDF_SUBS = {"≥": ">=", "≤": "<=", "−": "-", "→": "->", "“": '"', "”": '"', "’": "'", "‘": "'", "—": "-", "–": "-",
             "…": "...", "✓": "yes"}


def _pdf_text(s) -> str:
    text = str(s)
    for k, v in _PDF_SUBS.items():
        text = text.replace(k, v)
    text = text.encode("latin-1", "replace").decode("latin-1")
    return escape(text).replace("\n", "<br/>")


def to_pdf(blocks: list[dict], meta: dict) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), leftMargin=14 * mm, rightMargin=14 * mm, topMargin=14 * mm,
                            bottomMargin=16 * mm, title=meta["title"], author=meta.get("organisation") or "MadziHub",
                            subject=f"Report #{meta['id']}", creator="MadziHub")
    ss = getSampleStyleSheet()
    body = ParagraphStyle("b", parent=ss["BodyText"], fontSize=9, leading=12)
    cell = ParagraphStyle("c", parent=body, fontSize=8, leading=10)
    warn = ParagraphStyle("w", parent=body, backColor=colors.HexColor("#FFFBEB"), borderColor=colors.HexColor("#D97706"),
                          borderWidth=0.6, borderPadding=4, spaceBefore=4, spaceAfter=6)
    note = ParagraphStyle("n", parent=body, textColor=colors.HexColor("#4B5563"), fontName="Helvetica-Oblique")
    story = []
    status = meta["status"]
    for b in blocks:
        t = b["t"]
        if t == "h":
            story.append(Paragraph(_pdf_text(b["text"]), ss["Title"] if b["level"] == 1 else ss["Heading2"]))
        elif t == "p":
            story.append(Paragraph(_pdf_text(b["text"]), warn if b.get("tone") == "warn" else note if b.get("tone") == "note" else body))
        elif t == "kv":
            data = [[Paragraph(f"<b>{_pdf_text(k)}</b>", cell), Paragraph(_pdf_text(v), cell)] for k, v in b["items"]]
            tbl = Table(data, colWidths=[45 * mm, None], hAlign="LEFT")
            tbl.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("BOTTOMPADDING", (0, 0), (-1, -1), 2)]))
            story += [tbl, Spacer(1, 4)]
        elif t == "table":
            num = set(b.get("num", []))
            rstyle = ParagraphStyle("r", parent=cell, alignment=2)
            header = [Paragraph(f"<b>{_pdf_text(c)}</b>", cell) for c in b["columns"]]
            rows = [[Paragraph(_pdf_text(v), rstyle if i in num else cell) for i, v in enumerate(r)] for r in b["rows"]]
            story.append(Paragraph(f"<b>{_pdf_text(b['caption'])}</b>", body))
            tbl = Table([header] + (rows or [[Paragraph("None.", cell)] + [""] * (len(header) - 1)]), repeatRows=1)
            tbl.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D1D5DB")),
                                     ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F4F6")),
                                     ("VALIGN", (0, 0), (-1, -1), "TOP")]))
            story += [tbl, Spacer(1, 8)]

    def decorate(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#4B5563"))
        footer = (f"{meta.get('organisation') or ''}  |  Report #{meta['id']}  |  fingerprint "
                  f"{(meta.get('content_hash') or meta['data_hash'])[:16]}  |  page {canvas.getPageNumber()}")
        canvas.drawString(14 * mm, 8 * mm, _pdf_text(footer).replace("&amp;", "&"))
        if status not in ("approved", "published"):
            canvas.setFont("Helvetica-Bold", 44)
            canvas.setFillColor(colors.Color(0.8, 0.1, 0.1, alpha=0.12))
            canvas.translate(150 * mm, 100 * mm)
            canvas.rotate(28)
            canvas.drawCentredString(0, 0, "NOT APPROVED")
        canvas.restoreState()

    doc.build(story, onFirstPage=decorate, onLaterPages=decorate)
    return buf.getvalue()


# ── XLSX ────────────────────────────────────────────────────────────────────

def _num(v):
    try:
        return float(str(v).replace(",", "").rstrip("%"))
    except (TypeError, ValueError):
        return v


def to_xlsx(blocks: list[dict], meta: dict) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill

    wb = Workbook()
    ws = wb.active
    ws.title = "Report"
    bold = Font(bold=True)
    head_fill = PatternFill("solid", fgColor="F3F4F6")
    row = 1
    tables = []
    for b in blocks:
        t = b["t"]
        if t == "h":
            ws.cell(row, 1, b["text"]).font = Font(bold=True, size=14 if b["level"] == 1 else 12)
            row += 1
        elif t == "p":
            ws.cell(row, 1, b["text"]).alignment = Alignment(wrap_text=True)
            if b.get("tone") == "warn":
                ws.cell(row, 1).font = Font(bold=True, color="B45309")
            row += 1
        elif t == "kv":
            for k, v in b["items"]:
                ws.cell(row, 1, k).font = bold
                ws.cell(row, 2, v)
                row += 1
        elif t == "table":
            ws.cell(row, 1, b["caption"]).font = bold
            row += 1
            for j, c in enumerate(b["columns"], start=1):
                ws.cell(row, j, c).font = bold
                ws.cell(row, j).fill = head_fill
            row += 1
            num = set(b.get("num", []))
            for r in b["rows"]:
                for j, v in enumerate(r, start=1):
                    ws.cell(row, j, _num(v) if (j - 1) in num else v)
                row += 1
            tables.append(b)
        row += 1 if t in ("table", "kv") else 0
    ws.column_dimensions["A"].width = 48
    for col in "BCDEFGH":
        ws.column_dimensions[col].width = 18
    used = set()
    for b in tables:
        name = "".join(ch for ch in b["caption"] if ch not in '[]:*?/\\')[:28] or "Table"
        base, n = name, 2
        while name in used:
            name = f"{base[:25]} {n}"
            n += 1
        used.add(name)
        sh = wb.create_sheet(name)
        sh.append(b["columns"])
        for c in sh[1]:
            c.font = bold
            c.fill = head_fill
        num = set(b.get("num", []))
        for r in b["rows"]:
            sh.append([_num(v) if i in num else v for i, v in enumerate(r)])
        sh.freeze_panes = "A2"
        sh.column_dimensions["A"].width = 48
    wb.properties.title = meta["title"]
    wb.properties.creator = "MadziHub"
    wb.properties.description = f"Report #{meta['id']} ({meta['status']}), data fingerprint {meta['data_hash'][:16]}"
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


RENDERERS = {"html": (to_html, "text/html; charset=utf-8"),
             "pdf": (to_pdf, "application/pdf"),
             "xlsx": (to_xlsx, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")}
